[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "databricks-test"
version = "0.1.0"
description = "Test deployment"

[project.entry-points."databricks.jobs"]
hello_databricks = "src.hello_databricks:main"